version: "3.8"

networks:
      fabric_test:

services:
  ca_orderer:
    image: hyperledger/fabric-ca:1.5.6
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.orderer.intelijen.io
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=9054
    ports:
      - "9054:9054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./fabric-ca/orderer:/etc/hyperledger/fabric-ca-server
    container_name: ca.orderer.intelijen.io
    networks:
      - fabric_test
  
  ca_militer:
    image: hyperledger/fabric-ca:1.5.6
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.militer.intelijen.io
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./fabric-ca/militer:/etc/hyperledger/fabric-ca-server
    container_name: ca.militer.intelijen.io
    networks:
      - fabric_test
